SELECT
  HOUR(DATETIME) AS HOUR,
  COUNT(*) AS COUNT
FROM
  ANIMAL_OUTS
GROUP BY
  HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY
  HOUR

-- HOUR(DATETIME OR TIME) : 시간 값에서 "시간" 부분을 뽑아 0 ~ 23 사이의 정수로 표현한다.