SELECT
    PRODUCT.PRODUCT_CODE,
    SUM(SALES_AMOUNT) * PRODUCT.PRICE AS SALES
FROM
    PRODUCT,
    OFFLINE_SALE
WHERE PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY
    PRODUCT.PRODUCT_CODE
ORDER BY
    SALES DESC,
    PRODUCT.PRODUCT_CODE